---
title: "Secretary Problem"
date: "15/01/2022"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: cosmo
    code: hide
    df_print: paged
    code_download: true
    code_folding: show
editor_options: 
  chunk_output_type: inline
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
### Simulation
***

```{r, warning = FALSE}
#params
x_lim = 100
simulations = 10000
resmat = as.data.frame(matrix(ncol = 2, nrow = x_lim-1))


#simulation

for (v in 1:(x_lim-1)){
  
  boolean_vec = vector(mode = "logical", length = simulations)
  boolean_vec[1:simulations] = NA
  
  for (i in 1:simulations){
    
    x = sample(x = 1:x_lim, size = x_lim, replace = FALSE)
    
    train_max = max(x[1:v])
    total_max_index = which.max(x)
    
    if (min(which(x[(v+1:x_lim)] > train_max)) == Inf){
      
      boolean_vec[i] = x_lim == total_max_index
        
    } else{
      
      boolean_vec[i] = min(which(x[(v+1:x_lim)] > train_max)) + v == total_max_index
      
    }
    
  }

  resmat[v,1] = v
  resmat[v,2] = sum(boolean_vec)/simulations
    
}

```

```{r}
require(ggplot2)
require(ggthemes)

graph2 = ggplot(resmat, aes(x = V1, y = V2, colour = TRUE)) +
  geom_line(aes(lty = "solid")) +
  labs(title = "The Secretary Problem",
       subtitle = paste("Simulation for", x_lim, "applicants: Prob. of picking the best after skipping 'k'")) +
  guides(linetype = "none") + #removes linetype legend
  xlab("Applicants skipped before starting to decide") +
  ylab("Probability of picking the very best") +
  theme_bw() +
  theme(legend.position = "none") +
  scale_color_manual(values=c("blue"))
```

```{r}
library(gganimate)
graph2.animation = graph2 +
  transition_reveal(resmat$V1) #+ view_follow() #to move x axis

animate(graph2.animation, height = 500, width = 800, fps = 30, duration = 5,
        end_pause = 60, res = 125)
anim_save("simulation.gif")

```
